### ISSUE TITLE
Component Catalog

### ISSUE THREAD

**Issue by der-krueger** [namics/generator-nitro#147]
## Type of issue

* Documentation issue or request

The issue refers to the:

* nitro app (@nitro/app)

I'm currently using the [nitro-component-catalog](https://github.com/namics/nitro-component-catalog) which is refering to this project. But i can't find any similar function in the docs or code.
Is there any similar function available and if yes, how can i use it?

**Comment by ernscht** [comment]
Hi Thomas

Since the catalogue function is not compatible with Nitro Version 4, we have archived the catalogue repo and referred it to here.

However, a catalog function is only planned for the next major release, which is why this functionality has to be created manually at the moment.

If you have any further questions, please feel free to send us a PM.
