### ISSUE TITLE
gulp task 'minify-img' does not copy svg's

### ISSUE THREAD

**Issue by christianbueschi** [namics/generator-nitro#39]
I assume that the gulp task 'minify-img' should also copy svg-files from assets/img to public/assets/img provided through the svgo plugin. Unfortunately it doesn't. 

Gulp initially copies the folder (with containing svg's) but leaves it empty in public/assets/img and gulp breaks. If you run the task a second time, gulp breaks. If you manually copy the svg's to this folder, all gulp tasks pass through.

**Comment by ernscht** [comment]
Hi @christianbueschi.
`minify-img` minifies and copies SVG files by default – and this normally should work.
But i can confirm that there are some issues with (gulp-)imagemin and SVG files.
I guess your problem is related to individual SVG files (or the installation itself).
Is it possible to identify and send us the file who breaks the chain?
It would be great if we find a way to bypass the breaking error.

For now...
Because there is no way to [disable the SVG plugin](https://github.com/sindresorhus/gulp-imagemin/issues/63) i would try to find a working configuration
* disable the multipass option: `multipass: false`
* find the [SVGO options](https://github.com/svg/svgo) that works for your files: `svgoPlugins: [...]`

**Comment by christianbueschi** [comment]
Thanks @ernscht!
I identified the malfactor - it was a svg with an attached huge CDATA field. Although it is displayed properly, `minify-img` does not copy it and breaks the chain. After re-rendering the image (without the CDATA) everything works.

**Comment by ernscht** [comment]
Nice. Thanks for your feedback.
I'm still interested in this SVG to look for a solution witch doesn't break (-> PM)
