### ISSUE TITLE
make *.handlebars, *.hbs or *.mustache  as default file extension instead of .html

### ISSUE THREAD

**Issue by jackblackCH** [namics/generator-nitro#40]
if we use the correct file extensions it can be better recognized by IDE's for syntax highlightning and other features (helpers i.e).

i.e for the jetbrain products: https://github.com/dmarcotte/idea-handlebars

at least make it configurable via config.

**Comment by deniaz** [comment]
It is configurable.

```javascript
{
  'nitro': {
    'view_file_extension': 'hbs'
  }
}
```

It's implemented analogue to [how Terrific Micro](https://github.com/namics/terrific-micro/blob/master/config.json#L23) handles this but using the `nitro` identifier rather than `terrific`. I think for historic reasons we should keep the `html` file extensions as default. Also I'm not sure how Magnolia/.NET/CQ integrations handle different extensions.

Therefore I'll close this issue. If I'm mistaken or anyone insists on changing the default value please reopen the ticket for discussion.

/cc @ernscht
