### ISSUE TITLE
EditorConfig is not enforced

### ISSUE THREAD

**Issue by deniaz** [namics/generator-nitro#45]

**Comment by deniaz** [comment]
<img width="195" alt="screen shot 2015-10-06 at 10 49 42" src="https://cloud.githubusercontent.com/assets/698963/10304044/faf49056-6c17-11e5-842f-0949e2269503.png">

![I'm out](http://replygif.net/i/258.gif)

**Comment by floriangaechter** [comment]
I tried this plugin: https://github.com/ck86/gulp-lintspaces

The problem is, that if there are spaces (or tabs) where there shouldn't be the plugin immediately reports them. And at the moment we have such spaces in the JS-Blueprint:

<img width="111" alt="space" src="https://cloud.githubusercontent.com/assets/818120/10576141/64c1032c-7661-11e5-8f43-241cdfa2c386.png">

This results in a huge error list, depending on how many modules you have…

**Comment by deniaz** [comment]
Those spaces are correct, aren't they? I think it's more a problem of our Frontend Engineers not having the EditorConfig IDE Plugin installed... Not sure, though!

**Comment by ernscht** [comment]
I know of no way to really force EditorConfig(urations) in an IDE. 
The issue seems not to be Nitro related. This topic belongs rather to "Coding Guidelines". "Best Practices or "Project Settings".
So, a mention of the IDE Plugins in the file itself is probably the best thing we can do: [.editorconfig](https://github.com/namics/frontend-defaults/blob/master/editorconfig/frontend.editorconfig#L3)

There are other ways to achieve what you want (commit hooks, [sonarqube](http://www.sonarqube.org/), the mentioned gulp-lintspaces...) but i don't think that we should include this in Nitro.

**Comment by deniaz** [comment]
Well yes, I don't think we should include something like this in nitro either. Nevertheless it's quite an annoying issue. Do we have something like an "Recommended Toolset" section in know? Maybe people don't know about EditorConfig and that's why they don't use it.

**Comment by ernscht** [comment]
You are right. There could be more documentation. Noted.
For now ,.... how about a little snowball effect?
We both explain it to two people each. These people have to explain to two more people. That could work ;-)
