### ISSUE TITLE
Concatenate SCSS/LessCSS sources before compiling them?

### ISSUE THREAD

**Issue by SimonHarte** [namics/generator-nitro#65]
It seems that we're currently concatenating output CSS after files have been compiled which forces you to use "import" patterns for files such as `variables` and `mixins`.
I think it would make more sense to concatenate the files before compiling them, so you have more freedom in how you build globbing rules without the need of import patterns.

**Comment by SimonHarte** [comment]
We then also could omit all the `imports` concatenation and inserting them with `gulp-header`.

**Comment by dmodalek** [comment]
+1

**Comment by jackblackCH** [comment]
+1.

at the moment it's not possible (in a maintainable and convenient way) to use extends and mixins.

example: all typography is done with atoms and you wan't to extend your typography-atom in an molecule by ```:extend(.a-myexample-atom)```

**Comment by SimonHarte** [comment]
I know this change would defeat the purpose of caching since you'll always have to recompile everything, but I honestly don't think that this would have a huge impact on performance and make the build process incredibly more convenient to use. Also the import statement (`+`) isn't an official pattern as far as I know, which isn't really desirable either.

**Comment by floriangaechter** [comment]
Well, if we look at HTTP/2, concatenation will be obsolete anyway (at least in the way we use it now)… I don't know if it makes any sense to change that now and rewrite the whole asset generation in the near future.

**Comment by deniaz** [comment]
Slightly off topic: do we (as in Namics) actually have a plan on when and how to tackle http/2?

**Comment by floriangaechter** [comment]
We talked about it in the last "Wecker". But no specific plans yet.

**Comment by ernscht** [comment]
Back to the issue.
There are pros and cons for both ;-)
We decided to go this way concerning development performance and maintainability.
And we do not want to promote the use of "extend" because this could break the encapsulation of components in a undesirable way.

Using global variables & mixins (with the `+` pattern for all files) seems to be a transparent and clear way and promotes maintainability. 
But feel free, you don't have to. You may import your variables & mixins in every single file you need them. 
And, if you really need the extend feature you may import your dependencies as reference (at least this is possible with less).

**Comment by jackblackCH** [comment]
what are the cons ;-)?

**Comment by ernscht** [comment]
cons of what?
Let's set up a meeting.

**Comment by ernscht** [comment]
closing due to lack af activity. 
and version 1.0 should cover this anyway.
